---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.12
    container_name: homepage
    env_file:
      - .env
    ports:
      - $PORT:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: $PUID
      PGID: $PGID
