---
theme: dark
color: slate
target: _self

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
layout:
  NUC-01:
    style: row
    columns: 3
    icon: mdi-desktop-classic
  AMD:
    style: row
    columns: 3
    icon: mdi-laptop
  ARM64:
    style: row
    columns: 3
    icon: si-raspberrypi
  Other:
    style: row
    columns: 3
    icon: mdi-folder-multiple
  Laptop:
    style: row
    columns: 3
    icon: mdi-laptop
  Developer:
    style: row
    columns: 3
    icon: mdi-cog
  Icons & Emoji:
    style: row
    columns: 3
    icon: mdi-emoticon
